# Generated by Django 5.0.1 on 2024-01-03 10:25

import industrialdesignforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrialdesignforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialfile',
            name='file',
        ),
        migrations.AddField(
            model_name='industrialfile',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[industrialdesignforms.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='industrialfile',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[industrialdesignforms.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='industrialfile',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[industrialdesignforms.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='industrialfile',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[industrialdesignforms.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='industrialfile',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[industrialdesignforms.models.validate_pdf]),
        ),
    ]
