# Generated by Django 5.0.1 on 2024-01-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrialdesignforms', '0002_remove_industrialfile_file_industrialfile_file1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrialfile',
            name='file5',
        ),
    ]
