# Generated by Django 5.0 on 2023-12-08 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='document_type',
            field=models.CharField(choices=[('utility_model', 'Utility Model'), ('industrial_design', 'Industrial Design'), ('trademark', 'Trademark'), ('patent', 'Patent'), ('copyright', 'Copyright')], default='utility_model', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
