# Generated by Django 5.0 on 2023-12-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('campus', models.CharField(max_length=200)),
                ('department_type', models.CharField(choices=[('college_of_engineering_and_architecture', 'College of Engineering and Architecture'), ('college_of_information_technology_and_computing', 'College of Information Technology and Computing'), ('college_of_science_and_mathematics', 'College of Science and Mathematics'), ('college_of_science_and_technology_education', 'College of Science and Technology Education'), ('college_of_technology', 'College of Technology'), ('college_of_medicine', 'College of Medicine'), ('senior_high_school', 'Senior High School')], default=None, max_length=50, null=True)),
                ('user_role', models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('admin', 'Admin')], default='client', max_length=20, null=True)),
            ],
        ),
    ]
