# Generated by Django 5.0.1 on 2024-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patentform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentupload',
            name='abstract',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patentupload',
            name='invention_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patentupload',
            name='patent_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
