# Generated by Django 5.0.1 on 2024-01-31 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='uploads/')),
                ('file2', models.FileField(upload_to='uploads/')),
                ('file3', models.FileField(upload_to='uploads/')),
                ('file4', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback_text', models.TextField()),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='formupload.fileuploads')),
            ],
        ),
        migrations.CreateModel(
            name='UploadForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('patent_upload', 'Patent'), ('utility_model', 'Utility Model'), ('industrial_design', 'Industrial Design'), ('trade_mark', 'Trademark'), ('copy_right', 'Copyright')], default='patent_upload', max_length=50)),
                ('invention_title', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField(max_length=300, null=True)),
                ('authors', models.TextField(max_length=300, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fileuploads',
            name='upload_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='formupload.uploadforms'),
        ),
    ]
