# Generated by Django 5.0.1 on 2024-02-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0003_alter_uploadforms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploads',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='fileuploads',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='fileuploads',
            name='file4',
        ),
    ]
