# Generated by Django 5.0.1 on 2024-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0005_publication_remove_fileuploads_file1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='file3',
            field=models.ManyToManyField(related_name='file_uploads', to='formupload.publication'),
        ),
    ]
