# Generated by Django 5.0.1 on 2024-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0006_alter_fileuploads_file3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploads',
            old_name='file3',
            new_name='files',
        ),
        migrations.AlterField(
            model_name='fileuploads',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
