# Generated by Django 5.0.1 on 2024-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0007_rename_file3_fileuploads_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploads',
            name='files',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='fileuploads',
            name='files',
            field=models.FileField(default=False, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
