# Generated by Django 5.0.1 on 2024-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0008_remove_fileuploads_files_delete_publication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploads',
            old_name='files',
            new_name='file',
        ),
        migrations.CreateModel(
            name='Fileup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ManyToManyField(blank=True, related_name='upload_files', to='formupload.fileuploads')),
            ],
        ),
    ]
