# Generated by Django 5.0.1 on 2024-02-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0009_rename_files_fileuploads_file_fileup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploads',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
