# Generated by Django 5.0.1 on 2024-02-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0010_fileuploads_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='feedback',
            name='uploadform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formupload.uploadforms'),
        ),
    ]
