# Generated by Django 5.0.2 on 2024-02-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0010_fileuploads_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploads',
            name='file_name',
        ),
    ]
