# Generated by Django 5.0.1 on 2024-02-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0011_remove_feedback_file_upload_feedback_uploadform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='uploadform',
            new_name='upload_form',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='file_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
