# Generated by Django 5.0.1 on 2024-02-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0013_alter_feedback_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadforms',
            name='upload_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
