# Generated by Django 5.0.1 on 2024-02-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0017_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadforms',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
