# Generated by Django 5.0.1 on 2024-01-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_file_1', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('copyright_file_2', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('copyright_file_3', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('copyright_file_4', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
