# Generated by Django 5.0.1 on 2024-01-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilitymodelsform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilityfile',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='utilityfile',
            name='uploaded_by',
        ),
    ]
