# Generated by Django 5.0.1 on 2024-01-03 10:29

import utilitymodelsform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitymodelsform', '0002_remove_utilityfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilityfile',
            name='file',
        ),
        migrations.AddField(
            model_name='utilityfile',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[utilitymodelsform.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='utilityfile',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[utilitymodelsform.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='utilityfile',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[utilitymodelsform.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='utilityfile',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='industrialdesignfiles/', validators=[utilitymodelsform.models.validate_pdf]),
        ),
    ]
