# Generated by Django 5.0.1 on 2024-01-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
