# Generated by Django 5.0.1 on 2024-01-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
