# Generated by Django 5.0.1 on 2024-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_type',
            field=models.CharField(choices=[('engineering_architecture', 'College of Engineering and Architecture'), ('information_technology', 'College of Information Technology and Computing'), ('science_mathematics', 'College of Science and Mathematics'), ('science_tech_education', 'College of Science and Technology Education'), ('technology', 'College of Technology'), ('medicine', 'College of Medicine'), ('senior_high_school', 'Senior High School')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_campus',
            field=models.CharField(choices=[('ustp_alubijid', 'USTP Alubijid'), ('ustp_cagayan_de_oro', 'USTP Cagayan de Oro'), ('ustp_claveria', 'USTP Claveria'), ('ustp_balubal', 'USTP Balubal'), ('ustp_jasaan', 'USTP Jasaan'), ('ustp_oroquieta', 'USTP Oroquieta'), ('ustp_panaon', 'USTP Panaon'), ('ustp_villanueva', 'USTP Villanueva')], max_length=50),
        ),
    ]
