# Generated by Django 5.0.1 on 2024-02-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_department_type_alter_user_school_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
