# Generated by Django 5.0.1 on 2024-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_title', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField(max_length=300, null=True)),
                ('authors', models.TextField(max_length=300, null=True)),
                ('copyright_file_1', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('copyright_file_2', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('copyright_file_3', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('copyright_file_4', models.FileField(blank=True, null=True, upload_to='copyrightforms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
