# Generated by Django 5.0.1 on 2024-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadforms', '0002_uploadforms_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadforms',
            name='form_type',
            field=models.CharField(choices=[('patent_upload', 'Patent'), ('utility_model', 'Utility Model'), ('industrial_design', 'Industrial Design'), ('trade_mark', 'Trademark'), ('copy_right', 'Copyright')], default='patent_upload', max_length=50),
        ),
    ]
