# Generated by Django 4.2.6 on 2024-01-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadforms', '0003_uploadforms_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadforms',
            name='copyright_file_1',
        ),
        migrations.RemoveField(
            model_name='uploadforms',
            name='copyright_file_2',
        ),
        migrations.RemoveField(
            model_name='uploadforms',
            name='copyright_file_3',
        ),
        migrations.RemoveField(
            model_name='uploadforms',
            name='copyright_file_4',
        ),
        migrations.AddField(
            model_name='uploadforms',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('upload_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='uploadforms.uploadforms')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback_text', models.TextField()),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='uploadforms.fileuploads')),
            ],
        ),
    ]
