# Generated by Django 5.0.1 on 2024-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_recipient_alter_notification_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='upload_form',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
